site_name: Charlie and Wolfie Photography
site_description: Webpage for Charlie and Wolfie Photography
site_author: Cathleen Lapadat
site_url: https://nguye618.github.io/Charlie_and_Wolfie_Photography
theme:
  name: material
  logo: 'charlie.png'
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.prune
    - search.highlight
    - search.share
    - header.autohide
  font:
    text: Pacifico
plugins:
  - search
  - table-reader
  - glightbox
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
edit_uri: ""
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/charlie_and_wolfie_photography
    - icon: fontawesome/solid/paper-plane
      link: mailto:<charlieandwolfiephotography@gmail.com>
extra_css:
  - css/extra.css
extra_javascript:
    - js/image-carousel.js
nav:
  - Home: 'index.md'
  - Blog:
    - 8.14.2022: 'Blog.md'
  - Gallery:
    - Charlie: 'Gallery_Charlie.md'
    - Wolfies: 'Gallery_Wolfies.md'
    - Wildlife: 'Gallery_wildlife.md'
    - Landscapes: 'Gallery_landscapes.md'
  - About Me: 'about_me.md'
  - Contact: 'contact.md'